### ISSUE TITLE
Healthchecks should be exposed in a separate port/executor

### ISSUE THREAD

**Issue by worldtiki** [ExpediaGroup/pitchfork#187]
Under high load, Pitchfork may start to create a backlog of requests or even spill them over.
These requests can contain liveness checks used by loadbalancer/liveness probes which may lead to Pichfork to be marked as unhealthy and put out of service.

Spring Boot handles this nicely with the server.management.port property: https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-features.html#production-ready-customizing-management-server-port

**Comment by adriancole** [comment]
I get the overall concern, but if you are using a decent backend, and a
separate executor etc.. seems odd another port is also needed? did you run
into this I guess?

**Comment by worldtiki** [comment]
Yes. I had this issue a few weeks back but it was intermittent and I blamed it on unstable infra, but earlier this week someone else reported the same and after investigating we found the rejection of health check requests to be the root cause.

The easiest fix is by using the management.server.port property in Spring Boot (which starts a separate netty server).

I was considering applying this to the default settings but since this is a general problem and not specific to Pitchfork, the most adequate action is probably to just document this and close this issue.

**Comment by adriancole** [comment]
cool I was asking as I know we had to be careful what went on in i/o loops
but wasnt sure if load otherwise would be problem enough to overload the
i/o subsystem. ex in zipkin when we switched to reactive backend initially
we (we probably me ;)) screwed up up health checks like this.

**Comment by worldtiki** [comment]
Added a small note in the docs about this. Closing the ticket.
